// <auto-generated />
using System;
using HerbstSchulung.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HerbstSchulung.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017193030_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Fahrzeug", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("Baujahr")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hersteller")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Fahrzeuge", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Art")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.HasDiscriminator<int>("Art");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Auto", b =>
                {
                    b.HasBaseType("HerbstSchulung.EntityFramework.DataModel.Fahrzeug");

                    b.Property<int>("AnzahlTueren")
                        .HasColumnType("int");

                    b.Property<bool>("HatHybridantrieb")
                        .HasColumnType("bit");

                    b.ToTable("Autos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "AUT-1234ABCD",
                            Baujahr = 2020,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hersteller = "VW",
                            Modell = "Golf",
                            AnzahlTueren = 5,
                            HatHybridantrieb = true
                        });
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Lastkraftwagen", b =>
                {
                    b.HasBaseType("HerbstSchulung.EntityFramework.DataModel.Fahrzeug");

                    b.Property<int>("Achsen")
                        .HasColumnType("int");

                    b.Property<double>("ZuladungInTonnen")
                        .HasColumnType("float");

                    b.ToTable("Lastkraftwagen", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "LKW-9876WXYZ",
                            Baujahr = 2018,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hersteller = "MAN",
                            Modell = "TGX",
                            Achsen = 3,
                            ZuladungInTonnen = 18.5
                        });
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Student", b =>
                {
                    b.HasBaseType("HerbstSchulung.EntityFramework.DataModel.Person");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = "STD-ABCD2345",
                            Art = 0,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Max Mustermann",
                            Nationality = "DE",
                            School = "HTL Linz"
                        });
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Teacher", b =>
                {
                    b.HasBaseType("HerbstSchulung.EntityFramework.DataModel.Person");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = "TCR-EFGH6789",
                            Art = 1,
                            CreatedUtc = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Erika Musterfrau",
                            Nationality = "DE",
                            Subject = "Mathematik"
                        });
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Auto", b =>
                {
                    b.HasOne("HerbstSchulung.EntityFramework.DataModel.Fahrzeug", null)
                        .WithOne()
                        .HasForeignKey("HerbstSchulung.EntityFramework.DataModel.Auto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HerbstSchulung.EntityFramework.DataModel.Lastkraftwagen", b =>
                {
                    b.HasOne("HerbstSchulung.EntityFramework.DataModel.Fahrzeug", null)
                        .WithOne()
                        .HasForeignKey("HerbstSchulung.EntityFramework.DataModel.Lastkraftwagen", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
